-- CREAR TABLA
CREATE TABLE TAREAS(
    ID_TAREA INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
    ARCHIVADO BOOLEAN NOT NULL DEFAULT FALSE,
    DESCRIPCION VARCHAR(30) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL DEFAULT 'TODO',
        PRIMARY KEY (ID_TAREA),
        CHECK (ESTADO IN ('TODO', 'IN PROGRESS', 'DONE'))
);

-- INSERT TAREAS
INSERT INTO TAREAS (DESCRIPCION, ESTADO)
    VALUES ('Montar instalacion', 'TODO'),
           ('A la espera de recepcion', 'IN PROGRESS'),
           ('Comprar materiales', 'DONE');
